name: Publish

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

permissions:
  contents: write

jobs:
  package:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/package.yml

  publish-marketplace:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 25.x

      - uses: actions/download-artifact@v4
        with:
          name: vscode-extension-package
          path: dist/

      - run: npx @vscode/vsce publish --packagePath dist/*.vsix --pat ${{ secrets.VSCE_PAT }}

  publish-openvsx:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 25.x

      - uses: actions/download-artifact@v6
        with:
          name: vscode-extension-package
          path: dist/

      - run: npx ovsx publish dist/*.vsix
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}

  github-release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositoru
        uses: actions/checkout@v6

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep -oP '"version"\s*:\s*"\K[^"]+' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v4
        with:
          name: vscode-extension-package
          path: dist/

      - uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dist/todo-in-problem-tab-${{ steps.get_version.outputs.version }}.vsix
          asset_name: todo-in-problem-tab-${{ steps.get_version.outputs.version }}.vsix
          asset_content_type: application/vsix
