name: Publish to Open VSX Registry

on:
  workflow_run:
    workflows: ["Package"]
    types:
      - completed

jobs:
  publish-openvsx:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 25.x
      - uses: actions/download-artifact@v7
        with:
          name: vscode-extension-package
          path: dist/
      - run: npx ovsx publish dist/*.vsix
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
