name: Publish Marketplace

on:
  workflow_run:
    workflows: ["Package"]
    types:
      - completed

jobs:
  publish-marketplace:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 25.x
      - uses: actions/download-artifact@v7
        with:
          name: vscode-extension-package
          path: dist/
      - run: npm install -g vsce
      - run: npx vsce publish --pat ${{ secrets.VSCE_PAT }}
